version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.27
    - 15.0.0
  - dependency-name: aws-sdk
    versions:
    - 2.866.0
    - 2.888.0
    - 2.889.0
    - 2.890.0
    - 2.893.0
  - dependency-name: "@types/copy-webpack-plugin"
    versions:
    - 6.4.0
    - 6.4.1
  - dependency-name: css-loader
    versions:
    - 5.2.4
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: "@types/mini-css-extract-plugin"
    versions:
    - 1.4.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/workbox-webpack-plugin"
    versions:
    - 5.1.5
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
  - dependency-name: "@babel/register"
    versions:
    - 7.12.13
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
