version: '3.7'
services:
  '500':
    build:
      dockerfile: ./docker/Dockerfile.dev
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - app

networks:
  app:
