version: '3.7'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4567-4599:4567-4599"
      - "8080:8080"
    environment:
      - SERVICES=dynamodb,iam,lambda
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - PWD_USER=$PWD
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app
  environment:
    image: 500_environment:local
    container_name: 500_environment
    build:
      dockerfile: ./docker/Dockerfile.environment
      context: .
    volumes:
      - ./scripts/local/:/app/scripts/local
      - ./tf/local/:/app/tf/local
    depends_on:
      - localstack
    networks:
      - app
  apigateway_websocket:
    image: apigateway_websocket
    container_name: apigateway_websocket
    build:
      context: ./packages/local-api-gateway-websocket
    ports:
      - 7676:7676
    volumes:
      - ./packages/local-api-gateway-websocket/src:/app/src
    depends_on:
      - environment
    networks:
      - app

networks:
  app:
