FROM hashicorp/terraform

ENV AWS_ACCESS_KEY_ID=fake
ENV AWS_SECRET_ACCESS_KEY=fake
ENV AWS_DEFAULT_REGION=us-east-1

RUN apk add curl

# Install aws-cli
RUN apk -Uuv add groff less python py-pip
RUN pip install awscli
RUN apk --purge -v del py-pip
RUN rm /var/cache/apk/*

WORKDIR /app

ENTRYPOINT ["sh", "./scripts/local/build-env.sh"]
