FROM node:12 as build

WORKDIR /usr/src/app
ENV HOME /usr
ENV NODE_ENV localhost

# Install app dependencies
COPY package*.json ./

RUN npm ci

# Bundle app source
COPY . .

RUN npm run build:local

EXPOSE 8080
CMD [ "npm", "run", "start:local" ]
