name: PR Verify
on: [ pull_request ]
jobs:
  docker_lint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint
    steps:
      - uses: actions/checkout@v1
      - run: |
          hadolint Dockerfile
          hadolint docker/Dockerfile.dev
  npm_verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Add node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm_verify
        run: |
          npm ci
          npm run verify
        env:
          CI: true
